erDiagram
  "Task" {
    String id "🗝️"
    String title 
    String description 
    String picture "❓"
    TaskStatus status 
    Int hostId
    DateTime startDate 
    DateTime startTime 
    DateTime endDate "❓"
    Int locationId "❓"
    geography location "❓"
    String locationName "❓"
    CategoryType categories 
    Int amount "❓"
    Int current_amount "❓"
    String currency "❓"
    String requirements "❓"
    DateTime createdAt 
    DateTime updatedAt 
    }